var path = require('path')
var request = require('../common/error-request.js')

module.exports = Metadat

function Metadat(metadat) {
  if (metadat.name) {
    metadat.name = metadat.name.trim()
  }
  if (metadat.description) {
    metadat.description = metadat.description.trim()
  }
  this.data = metadat
}

Metadat.prototype.create = function (cb) {
  var self = this
  var options = {
    uri: '/api/metadat',
    method: 'POST',
    json: this.data
  }
  request(options, function (err, resp, json) {
    if (err) return cb(err)
    self.data.id = json.id
    return cb(null, resp, json)
  })
}

/** Functions to act upon metadats **/
Metadat.query = function (params, cb) {
  // Parameters
  // params: dict
  //  keys represent the fields to filter upon
  if (!params) {
    return cb(new Error('Give at least one param or use the `all` function.'))
  }
  var options = {
    uri: '/api/metadat',
    qs: params,
    method: 'GET',
    json: true
  }

  request(options, function (err, resp, json) {
    if (err) return cb(err)
    return cb(null, resp, json)
  })
}


/**
 * TODO: this should be auto-generated by the frontend.
 * ...like a REST consumer js api. that has to exist, right?
 */
Metadat.all = function (cb) {
  var options = {
    uri: '/api/metadat',
    method: 'GET',
    json: true
  }
  request(options, function (err, resp, json) {
    if (err) return cb(err)
    return cb(null, resp, json)
  })
}

Metadat.get = function (metadatId, cb) {
  var options = {
    uri: '/api/metadat/' + metadatId,
    method: 'GET',
    json: true
  }
  request(options, function (err, resp, json) {
    if (err) {
      return cb(new Error('Could not get that dat, are you sure the ID is right?'))
    }
    return cb(null, resp, json)
  })
}
